### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by orbitjules** [eflorit/bloodpoints-spender#1]
It keeps telling me that there are no nodes to click, even though there are

**Comment by eflorit** [comment]
Heya. I made a fix recently but never uploaded it on here since I didn't know if anyone was using it. It should now work if you get the latest version.

**Comment by orbitjules** [comment]
Hey, thanks for the response!

Did you update the pre-compiled version as well, or just the one you have to build yourself? Because the pre compiled one still doesn't seem to be working, and I have no clue how to build this myself.

**Comment by eflorit** [comment]
I did both. I actually use this same precompiled version myself (used it again today) and it works for me.

- Did you make sure to unzip the entire folder before running the exe file? (don't run it straight from the archive)
- Did you make sure your game runs in `1920x1080`?
- Are your graphics on `Low`?

**Comment by orbitjules** [comment]
Yes, all of these prerequisites are met, but the program keeps outputting that there are no nodes to click.

![image](https://user-images.githubusercontent.com/73449900/200578051-5c74f12c-04e1-4199-bcf5-4a75aa8773ce.png)

https://i.imgur.com/ndTfb6j.jpeg

**Comment by eflorit** [comment]
Okay.
- Did you make sure you turned off any filter your graphics card may add (Nvidia, etc)?
- Do you make sure to stay on the bloodweb screen during this whole time?

Feel free to share your `tmp-screenshot.png` so I can take try to identify what's wrong in it

**Comment by orbitjules** [comment]
Thank you for the help! I didn't realize my reshade was messing the program up. It's working now!
